# Generated by Django 5.1.15 on 2026-09-04 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], default='Neutral', max_length=20)),
                ('sentiment_breakdown', models.JSONField(default=dict, help_text="Breakdown percentages e.g. {'positive': 33, 'neutral': 0, 'negative': 67}")),
                ('topics', models.JSONField(default=list, help_text="List of extracted topic labels e.g. ['Response Time', 'Customer Service']")),
                ('summary', models.TextField(help_text='AI-generated executive feedback summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='surveys.survey')),
            ],
            options={
                'db_table': 'ai_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
