import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart3, Check, ChevronLeft, ClipboardList, FileText, LayoutDashboard, LogOut, MessageSquare, Plus, Send, Sparkles, X } from 'lucide-react';
import './styles.css';

const initialSurvey = {
  id: 1, title: 'Customer Service Feedback Survey',
  description: 'Please provide feedback about your recent customer service experience.', status: 'Published',
  questions: [
    { id: 1, text: 'How satisfied are you with our service?', type: 'Rating', required: true },
    { id: 2, text: 'How would you rate the response time?', type: 'Multiple choice', options: ['Excellent', 'Good', 'Fair', 'Poor'], required: true },
    { id: 3, text: 'What could we improve?', type: 'Text', required: false }
  ]
};
const feedback = [
  { name: 'Response #001', text: 'Overall the service was good, but the response time was slow.', sentiment: 'Negative', date: 'Aug 30, 2026' },
  { name: 'Response #002', text: 'The staff were very helpful and friendly.', sentiment: 'Positive', date: 'Aug 30, 2026' },
  { name: 'Response #003', text: 'I had to wait too long before receiving support.', sentiment: 'Negative', date: 'Aug 29, 2026' }
];

function App() {
  const [user, setUser] = useState(null); const [page, setPage] = useState('dashboard');
  const [survey, setSurvey] = useState(initialSurvey); const [draft, setDraft] = useState(null);
  const [modal, setModal] = useState(null); const [answers, setAnswers] = useState({}); const [notice, setNotice] = useState('');
  const [loading, setLoading] = useState(false); const [showEmpty, setShowEmpty] = useState(false); const [showError, setShowError] = useState(false);
  const login = (role) => { setLoading(true); setTimeout(() => { setUser(role); setPage(role === 'respondent' ? 'available' : 'dashboard'); setLoading(false); }, 550); };
  const nav = (to) => { setNotice(''); setPage(to); };
  const saveDraft = () => { if (!draft.title.trim()) { setNotice('Survey title is required.'); return; } setSurvey({ ...draft, status: draft.status || 'Draft' }); nav('editor'); };
  const addQuestion = (q) => { setSurvey(s => ({ ...s, questions: [...s.questions, { ...q, id: Date.now() }] })); nav('editor'); };
  const publish = () => { setSurvey(s => ({ ...s, status: 'Published' })); setModal(null); nav('published'); };
  const submit = () => { const missing = survey.questions.filter(q => q.required && !answers[q.id]); if (missing.length) { setNotice('Please answer all required questions.'); return; } setModal('submit'); };
  if (!user) return <Login loading={loading} onLogin={login} />;
  const titles = { dashboard: 'Dashboard', available: 'Available surveys', create: 'Create survey', editor: 'Survey editor', preview: 'Survey preview', detail: 'Survey details', form: 'Customer Service Feedback Survey', results: 'Survey results', feedback: 'Feedback', analysis: 'AI analysis', published: 'Published successfully', submitted: 'Response submitted' };
  return <div className="app"><aside><div className="brand"><span className="brand-icon"><MessageSquare size={19}/></span> InsightFlow</div><div className="role">{user}</div><nav>
    {user !== 'respondent' && <Nav icon={<LayoutDashboard/>} label="Dashboard" active={page==='dashboard'} onClick={() => nav('dashboard')}/>} 
    {user === 'researcher' && <Nav icon={<ClipboardList/>} label="Surveys" active={['create','editor','preview','published'].includes(page)} onClick={() => nav('dashboard')}/>} 
    {user === 'respondent' && <Nav icon={<ClipboardList/>} label="Available surveys" active={['available','detail','form','submitted'].includes(page)} onClick={() => nav('available')}/>} 
    {user === 'manager' && <><Nav icon={<BarChart3/>} label="Survey results" active={['results','feedback','analysis'].includes(page)} onClick={() => nav('results')}/><Nav icon={<Sparkles/>} label="AI analysis" active={page==='analysis'} onClick={() => nav('analysis')}/></>}
  </nav><button className="logout" onClick={() => setUser(null)}><LogOut/> Log out</button></aside><main><header><div><p className="eyebrow">{user === 'researcher' ? 'RESEARCH WORKSPACE' : user === 'manager' ? 'ANALYTICS WORKSPACE' : 'YOUR FEEDBACK'}</p><h1>{titles[page]}</h1></div><div className="avatar">{user[0].toUpperCase()}</div></header>
  {notice && <div className="alert"><span>{notice}</span><button onClick={() => setNotice('')}><X size={16}/></button></div>}
  {page === 'dashboard' && (user === 'manager' ? <ManagerDashboard onResults={() => nav('results')} /> : <ResearcherDashboard survey={survey} onCreate={() => {setDraft({title:'',description:'',questions:[],status:'Draft'});nav('create')}} onEdit={() => nav('editor')} empty={showEmpty} error={showError} setEmpty={setShowEmpty} setError={setShowError}/>)}
  {page === 'create' && <SurveyInfo value={draft} setValue={setDraft} onCancel={() => nav('dashboard')} onSave={saveDraft}/>} 
  {page === 'editor' && <Editor survey={survey} setSurvey={setSurvey} onAdd={() => nav('addQuestion')} onPreview={() => nav('preview')} onPublish={() => setModal('publish')}/>} 
  {page === 'addQuestion' && <QuestionForm onCancel={() => nav('editor')} onSave={addQuestion}/>} 
  {page === 'preview' && <Preview survey={survey} onBack={() => nav('editor')} onPublish={() => setModal('publish')}/>} 
  {page === 'available' && <Available survey={survey} onOpen={() => nav('detail')}/>} {page === 'detail' && <Detail survey={survey} onStart={() => nav('form')} onBack={() => nav('available')}/>} 
  {page === 'form' && <SurveyForm survey={survey} answers={answers} setAnswers={setAnswers} onSubmit={submit} onBack={() => nav('detail')}/>} 
  {page === 'results' && <Results onFeedback={() => nav('feedback')} onAnalysis={() => nav('analysis')}/>} {page === 'feedback' && <Feedback onAnalysis={() => nav('analysis')}/>} {page === 'analysis' && <Analysis/>}
  {page === 'published' && <Success title="Survey published successfully" text="Your survey is now available for respondents." action="Back to dashboard" onAction={() => nav('dashboard')}/>} {page === 'submitted' && <Success title="Your response has been submitted" text="Thank you for taking the time to share your feedback." action="View available surveys" onAction={() => nav('available')}/>} 
  </main>{modal && <Modal title={modal==='publish'?'Publish this survey?':'Submit your response?'} text={modal==='publish'?'Are you sure you want to publish this survey? Respondents will be able to access it.':'You will not be able to edit your answers after submission.'} confirm={modal==='publish'?'Publish survey':'Submit response'} onCancel={() => setModal(null)} onConfirm={modal==='publish'?publish:() => {setModal(null);nav('submitted')}}/>}</div>;
}
const Nav=({icon,label,active,onClick})=><button className={'nav '+(active?'active':'')} onClick={onClick}>{icon}<span>{label}</span></button>;
function Login({onLogin,loading}) { const [email,setEmail]=useState('researcher@insightflow.com'); const [error,setError]=useState(''); return <div className="login-page"><section className="login-card"><div className="login-logo"><MessageSquare/> InsightFlow</div><p className="eyebrow">AI CUSTOMER FEEDBACK PLATFORM</p><h1>Welcome back</h1><p className="muted">Sign in to explore the interactive prototype.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input type="password" defaultValue="password"/></label>{error&&<p className="field-error">{error}</p>}<button className="primary wide" disabled={loading} onClick={()=>!email.includes('@')?setError('Enter a valid email address.'):onLogin('researcher')}>{loading?'Signing in…':'Sign in'}</button><div className="demo"><span>Try a demo role</span><button onClick={()=>onLogin('researcher')}>Researcher</button><button onClick={()=>onLogin('respondent')}>Respondent</button><button onClick={()=>onLogin('manager')}>Manager</button></div></section><section className="login-aside"><div><span className="spark"><Sparkles/></span><h2>Turn feedback into better decisions.</h2><p>Create surveys, collect customer insights and understand feedback with mock AI analysis.</p></div></section></div> }
function ResearcherDashboard({survey,onCreate,onEdit,empty,error,setEmpty,setError}) {return <><div className="toolbar"><p className="muted">Create and manage your customer feedback surveys.</p><button className="primary" onClick={onCreate}><Plus size={18}/> Create survey</button></div><div className="state-controls"><button onClick={()=>{setEmpty(!empty);setError(false)}}>Toggle empty</button><button onClick={()=>{setError(!error);setEmpty(false)}}>Toggle error</button></div>{error?<div className="state-card"><h3>Couldn’t load surveys</h3><p>Something went wrong. Please try again.</p><button className="secondary" onClick={()=>setError(false)}>Try again</button></div>:empty?<div className="state-card"><ClipboardList size={36}/><h3>No surveys yet</h3><p>Create your first survey to start collecting feedback.</p><button className="primary" onClick={onCreate}>Create survey</button></div>:<div className="card table-card"><table><thead><tr><th>Survey</th><th>Status</th><th>Questions</th><th>Responses</th><th></th></tr></thead><tbody><tr><td><b>{survey.title}</b><small>{survey.description}</small></td><td><Badge type={survey.status}/></td><td>{survey.questions.length}</td><td>{survey.status==='Published'?3:'—'}</td><td><button className="link" onClick={onEdit}>Edit</button></td></tr></tbody></table></div>}</>}
function SurveyInfo({value,setValue,onCancel,onSave}) {return <div className="form-card card"><h2>Survey details</h2><p className="muted">Start with the basics. You can add questions next.</p><label>Survey title <em>*</em><input placeholder="e.g. Customer service feedback" value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/></label><label>Description<textarea placeholder="Tell respondents what this survey is about" value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></label><div className="actions"><button className="secondary" onClick={onCancel}>Cancel</button><button className="primary" onClick={onSave}>Save and continue</button></div></div>}
function Editor({survey,setSurvey,onAdd,onPreview,onPublish}) {const remove=id=>setSurvey({...survey,questions:survey.questions.filter(q=>q.id!==id)});return <><div className="toolbar"><div><h2>{survey.title}</h2><p className="muted">{survey.description||'No description added.'}</p></div><div><button className="secondary" onClick={onPreview}>Preview</button> <button className="primary" onClick={onPublish}>Publish</button></div></div><div className="card editor"><div className="section-heading"><div><h2>Questions</h2><p className="muted">{survey.questions.length} question{survey.questions.length!==1?'s':''}</p></div><button className="secondary" onClick={onAdd}><Plus size={17}/> Add question</button></div>{survey.questions.length===0?<div className="empty-inline">No questions yet. Add one to build your survey.</div>:survey.questions.map((q,i)=><div className="question-row" key={q.id}><span className="number">{i+1}</span><div><b>{q.text}</b><small>{q.type} {q.required&&'· Required'}</small></div><button className="link danger" onClick={()=>remove(q.id)}>Delete</button></div>)}</div></>}
function QuestionForm({onCancel,onSave}) {const [q,setQ]=useState({text:'',type:'Rating',required:true,options:['Excellent','Good','Fair','Poor']}); return <div className="form-card card"><h2>Add question</h2><label>Question text <em>*</em><input value={q.text} onChange={e=>setQ({...q,text:e.target.value})} placeholder="Type your question"/></label><label>Question type<select value={q.type} onChange={e=>setQ({...q,type:e.target.value})}><option>Rating</option><option>Multiple choice</option><option>Text</option></select></label>{q.type==='Multiple choice'&&<label>Options<input value={q.options.join(', ')} onChange={e=>setQ({...q,options:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/><small>Separate options with commas.</small></label>}<label className="toggle"><input type="checkbox" checked={q.required} onChange={e=>setQ({...q,required:e.target.checked})}/><span>Required question</span></label><div className="actions"><button className="secondary" onClick={onCancel}>Cancel</button><button className="primary" onClick={()=>q.text.trim()&&onSave(q)}>Save question</button></div></div>}
function Preview({survey,onBack,onPublish}) {return <div className="preview"><div className="toolbar"><div><h2>Preview survey</h2><p className="muted">This is how respondents will see your survey.</p></div><button className="secondary" onClick={onBack}><ChevronLeft size={17}/> Back to edit</button></div><SurveyFields survey={survey} answers={{}} setAnswers={()=>{}} readOnly/><button className="primary" onClick={onPublish}>Publish survey</button></div>}
function Available({survey,onOpen}) {return <><p className="muted page-intro">Choose a survey and share your experience.</p><div className="survey-tile card"><div className="survey-icon"><ClipboardList/></div><div><Badge type="Published"/><h2>{survey.title}</h2><p>{survey.description}</p><small>{survey.questions.length} questions · Takes about 2 minutes</small></div><button className="primary" onClick={onOpen}>View survey</button></div></>}
function Detail({survey,onStart,onBack}) {return <div className="detail card"><button className="back" onClick={onBack}><ChevronLeft size={17}/> All surveys</button><div className="survey-icon"><ClipboardList/></div><Badge type="Published"/><h1>{survey.title}</h1><p>{survey.description}</p><hr/><div className="detail-stats"><div><b>{survey.questions.length}</b><span>questions</span></div><div><b>2 min</b><span>estimated time</span></div></div><button className="primary" onClick={onStart}>Start survey <Send size={16}/></button></div>}
function SurveyFields({survey,answers,setAnswers,readOnly}) {return <div className="respond-form card"><h2>{survey.title}</h2><p className="muted">{survey.description}</p>{survey.questions.map((q,i)=><div className="field-question" key={q.id}><label>{i+1}. {q.text} {q.required&&<em>*</em>}</label>{q.type==='Rating'?<div className="ratings">{[1,2,3,4,5].map(n=><button type="button" disabled={readOnly} className={answers[q.id]===n?'selected':''} onClick={()=>setAnswers({...answers,[q.id]:n})} key={n}>{n}</button>)}</div>:q.type==='Multiple choice'?<div className="options">{q.options.map(o=><label key={o}><input type="radio" disabled={readOnly} name={'q'+q.id} checked={answers[q.id]===o} onChange={()=>setAnswers({...answers,[q.id]:o})}/>{o}</label>)}</div>:<textarea disabled={readOnly} value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} placeholder="Share your thoughts..."/>}</div>)}</div>}
function SurveyForm({survey,answers,setAnswers,onSubmit,onBack}) {return <><button className="back page-back" onClick={onBack}><ChevronLeft size={17}/> Back</button><SurveyFields survey={survey} answers={answers} setAnswers={setAnswers}/><button className="primary submit" onClick={onSubmit}>Submit response</button></>}
function ManagerDashboard({onResults}) {return <><p className="muted page-intro">An overview of customer feedback across your published surveys.</p><div className="metrics"><Metric label="Total surveys" value="12"/><Metric label="Total responses" value="248"/><Metric label="Average rating" value="3.8 / 5"/><Metric label="Positive sentiment" value="33%"/></div><div className="split"><div className="card"><h2>Sentiment overview</h2><div className="bars"><Bar label="Positive" value="33%" color="green"/><Bar label="Neutral" value="0%" color="gray"/><Bar label="Negative" value="67%" color="red"/></div></div><div className="card"><h2>Top topics</h2><div className="topics"><span>Response Time</span><span>Customer Service</span><span>Staff Support</span></div><button className="link" onClick={onResults}>View survey results →</button></div></div></>}
function Results({onFeedback,onAnalysis}) {return <><div className="toolbar"><div><h2>Customer Service Feedback Survey</h2><p className="muted">Published Aug 21, 2026</p></div><button className="primary" onClick={onAnalysis}><Sparkles size={16}/> View AI analysis</button></div><div className="metrics"><Metric label="Total responses" value="3"/><Metric label="Average rating" value="3.7 / 5"/><Metric label="Positive sentiment" value="33%"/></div><div className="split"><div className="card"><h2>Rating distribution</h2><div className="bars"><Bar label="5 stars" value="33%" color="green"/><Bar label="4 stars" value="33%" color="blue"/><Bar label="2 stars" value="34%" color="orange"/></div></div><div className="card"><h2>Recent feedback</h2>{feedback.slice(0,2).map(x=><p className="quote" key={x.name}>“{x.text}”</p>)}<button className="link" onClick={onFeedback}>View all feedback →</button></div></div></>}
function Feedback({onAnalysis}) {return <><div className="toolbar"><p className="muted">3 responses for Customer Service Feedback Survey</p><button className="secondary" onClick={onAnalysis}><Sparkles size={16}/> AI analysis</button></div><div className="card feedback-list">{feedback.map(x=><div className="feedback-item" key={x.name}><div><b>{x.name}</b><small>{x.date}</small></div><Badge type={x.sentiment}/><p>“{x.text}”</p></div>)}</div></>}
function Analysis() {return <><div className="ai-hero"><span className="spark"><Sparkles/></span><div><p className="eyebrow">MOCK AI INSIGHTS</p><h2>Customer Service Feedback Survey</h2><p>Analysis based on 3 responses</p></div></div><div className="split"><div className="card"><h2>Sentiment analysis</h2><div className="bars"><Bar label="Positive" value="33%" color="green"/><Bar label="Neutral" value="0%" color="gray"/><Bar label="Negative" value="67%" color="red"/></div></div><div className="card"><h2>Topics found</h2><div className="topics"><span>Response Time</span><span>Customer Service</span><span>Staff Support</span></div></div></div><div className="card summary"><div><Sparkles size={21}/><h2>AI summary</h2></div><p>Most respondents were satisfied with staff support, but response time was a recurring concern.</p></div></>}
const Metric=({label,value})=><div className="metric card"><p>{label}</p><b>{value}</b></div>; const Bar=({label,value,color})=><div className="bar-row"><span>{label}</span><div><i className={color} style={{width:value}}/></div><b>{value}</b></div>; const Badge=({type})=><span className={'badge '+String(type).toLowerCase().replace(' ','-')}>{type}</span>;
function Success({title,text,action,onAction}) {return <div className="success card"><span><Check size={30}/></span><h2>{title}</h2><p>{text}</p><button className="primary" onClick={onAction}>{action}</button></div>}; function Modal({title,text,confirm,onCancel,onConfirm}) {return <div className="overlay"><div className="modal"><h2>{title}</h2><p>{text}</p><div className="actions"><button className="secondary" onClick={onCancel}>Cancel</button><button className="primary" onClick={onConfirm}>{confirm}</button></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
